### ISSUE TITLE
Missing ruby version requirement

### ISSUE THREAD

**Issue by jammer** [wingyu/rbattlenet#5]
Seems like this gem requires Ruby 2.0+, but you don't specify it in the gemspec so it installs into 1.9

Attempting to run simple ruby file with only require 'rbattlenet' results into error

```
/var/lib/gems/1.9.1/gems/rbattlenet-1.1.0/lib/rbattlenet.rb:1:in `require_relative': /var/lib/gems/1.9.1/gems/rbattlenet-1.1.0/lib/rbattlenet/rbattlenet.rb:37: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
  def self.authenticate(api_key:)
                                ^
/var/lib/gems/1.9.1/gems/rbattlenet-1.1.0/lib/rbattlenet/rbattlenet.rb:46: syntax error, unexpected tLABEL, expecting ')'
  def self.set_region(region:, locale:)
                             ^
/var/lib/gems/1.9.1/gems/rbattlenet-1.1.0/lib/rbattlenet/rbattlenet.rb:50: syntax error, unexpected keyword_end, expecting $end
        from /var/lib/gems/1.9.1/gems/rbattlenet-1.1.0/lib/rbattlenet.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from test.rb:1:in `<main>'
```

**Comment by wingyu** [comment]
@jammer thanks for letting me know, i'll have a look into it tomorrow

**Comment by wingyu** [comment]
@jammer this issue should now be resolved, let me know if it crops up again
